version: "3"
services:
  irc:
    image: inspircd/inspircd-docker
    ports:
      - 6697:6697
    volumes:
      - /data/irc/conf:/inspircd/conf
      - /etc/letsencrypt/live/irc.chalmers.it/fullchain.pem:/inspircd/ssl/cert.pem
      - /etc/letsencrypt/live/irc.chalmers.it/privkey.pem:/inspircd/ssl/key.pem
